// Database types for GrowLocal 360
// These will be generated by Supabase CLI later, but we define them manually for now

export type WebsiteType = 'single_location' | 'multi_location' | 'microsite';
export type UserRole = 'admin' | 'user';
export type JobStatus = 'draft' | 'queued' | 'approved' | 'deployed' | 'rejected';

export interface Organization {
  id: string;
  name: string;
  slug: string;
  created_at: string;
  updated_at: string;
}

export interface Profile {
  id: string;
  user_id: string;
  organization_id: string;
  role: UserRole;
  full_name: string | null;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface Site {
  id: string;
  organization_id: string;
  name: string;
  slug: string;
  website_type: WebsiteType;
  domain: string | null;
  primary_gbp_category_id: string | null;
  is_active: boolean;
  settings: SiteSettings;
  created_at: string;
  updated_at: string;
}

export interface SiteSettings {
  brand_color?: string;
  logo_url?: string;
  phone?: string;
  email?: string;
}

export interface Location {
  id: string;
  site_id: string;
  name: string;
  slug: string;
  address_line1: string;
  address_line2: string | null;
  city: string;
  state: string;
  zip_code: string;
  country: string;
  latitude: number | null;
  longitude: number | null;
  phone: string | null;
  is_primary: boolean;
  gbp_place_id: string | null;
  gbp_account_id: string | null;
  gbp_location_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface GBPCategory {
  id: string;
  gcid: string; // Google Category ID
  name: string;
  display_name: string;
  parent_gcid: string | null;
  service_types: string[];
  created_at: string;
}

export interface SiteCategory {
  id: string;
  site_id: string;
  gbp_category_id: string;
  is_primary: boolean;
  sort_order: number;
  created_at: string;
}

export interface Service {
  id: string;
  site_id: string;
  site_category_id: string;
  name: string;
  slug: string;
  description: string | null;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface JobSnap {
  id: string;
  site_id: string;
  location_id: string;
  service_id: string | null;
  created_by: string;
  status: JobStatus;
  title: string | null;
  description: string | null;
  ai_generated_title: string | null;
  ai_generated_description: string | null;
  approved_by: string | null;
  approved_at: string | null;
  deployed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface JobSnapMedia {
  id: string;
  job_snap_id: string;
  storage_path: string;
  file_name: string;
  ai_generated_name: string | null;
  alt_text: string | null;
  mime_type: string;
  file_size: number;
  width: number | null;
  height: number | null;
  exif_data: Record<string, unknown> | null;
  sort_order: number;
  created_at: string;
}

export interface SocialConnection {
  id: string;
  site_id: string;
  platform: 'google_business' | 'facebook' | 'instagram' | 'youtube';
  account_id: string;
  account_name: string;
  access_token: string;
  refresh_token: string | null;
  token_expires_at: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// Extended types with relations
export interface SiteWithRelations extends Site {
  locations?: Location[];
  categories?: (SiteCategory & { gbp_category: GBPCategory })[];
  services?: Service[];
}

export interface LocationWithRelations extends Location {
  site?: Site;
  job_snaps?: JobSnap[];
}

export interface JobSnapWithRelations extends JobSnap {
  media?: JobSnapMedia[];
  location?: Location;
  service?: Service;
  created_by_profile?: Profile;
}
