// Database types for GrowLocal 360
// These will be generated by Supabase CLI later, but we define them manually for now

export type WebsiteType = 'single_location' | 'multi_location' | 'microsite';
export type UserRole = 'owner' | 'admin' | 'user';
export type JobStatus = 'draft' | 'queued' | 'approved' | 'deployed' | 'rejected';
export type TemplateId = 'local-service-pro';
export type SiteStatus = 'building' | 'active' | 'paused' | 'failed' | 'suspended' | 'archived';

// Build progress tracking for site content generation
export interface SiteBuildProgress {
  total_tasks: number;
  completed_tasks: number;
  current_task: string;
  started_at: string;
  scope_type?: GenerationScope['type'];
}

// Selective content regeneration scope
export type GenerationScope =
  | { type: 'full' }
  | { type: 'core-pages'; pages?: ('home' | 'about' | 'contact')[] }
  | { type: 'services'; serviceIds: string[] }
  | { type: 'categories'; categoryIds: string[] }
  | { type: 'service-areas'; serviceAreaIds: string[] }
  | { type: 'brands'; brandIds: string[] }
  | { type: 'neighborhoods'; neighborhoodIds: string[] }
  | { type: 'reviews' };

export interface Organization {
  id: string;
  name: string;
  slug: string;
  created_at: string;
  updated_at: string;
}

export interface Profile {
  id: string;
  user_id: string;
  organization_id: string;
  role: UserRole;
  full_name: string | null;
  avatar_url: string | null;
  bio: string | null;
  title: string | null;
  show_on_site: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface Invitation {
  id: string;
  organization_id: string;
  email: string;
  role: UserRole;
  invited_by: string | null;
  token: string;
  site_ids: string[];
  accepted_at: string | null;
  expires_at: string;
  created_at: string;
}

export interface ProfileSiteAssignment {
  id: string;
  profile_id: string;
  site_id: string;
  created_at: string;
}

export interface StaffMember {
  id: string;
  organization_id: string;
  full_name: string;
  title: string | null;
  email: string | null;
  phone: string | null;
  bio: string | null;
  avatar_url: string | null;
  show_on_site: boolean;
  display_order: number;
  is_active: boolean;
  schedule_token: string | null;
  created_at: string;
  updated_at: string;
}

export interface StaffSiteAssignment {
  id: string;
  staff_member_id: string;
  site_id: string;
}

export interface Site {
  id: string;
  organization_id: string;
  name: string;
  slug: string;
  website_type: WebsiteType;
  template_id: TemplateId;
  domain: string | null;
  custom_domain: string | null;
  custom_domain_verified: boolean;
  vercel_domain_config: Record<string, unknown> | null;
  primary_gbp_category_id: string | null;
  is_active: boolean;
  // Site status and build progress
  status: SiteStatus;
  build_progress: SiteBuildProgress | null;
  status_message: string | null;
  status_updated_at: string;
  settings: SiteSettings;
  created_at: string;
  updated_at: string;
}

export interface SiteSettings {
  // Branding & Contact
  brand_color?: string;
  secondary_color?: string;
  cta_color?: string;
  logo_url?: string;
  phone?: string;
  email?: string;
  core_industry?: string;
  cta_text?: string;
  // Review Data
  google_average_rating?: number;
  google_total_reviews?: number;
  review_source_url?: string;
  // About the Business
  business_description?: string;
  credentials?: string;
  // Voice & Tone
  tone_values?: string[];
  point_of_view?: string;
  words_to_use?: string;
  words_to_avoid?: string;
  // Audience
  target_audience?: string;
  // Reference Material
  writing_samples?: string;
  onboarding_notes?: string;
  // Specific Requests
  specific_requests?: string;
  // Local Details
  local_details?: string;
  // Image Preferences
  default_image_style?: string;
  brand_style_guide?: string;
  // Google Search Console
  gsc_property_url?: string;
  gsc_last_synced_at?: string;
  gsc_connected?: boolean;
  // Microsite targeting
  microsite_target_city?: string;
  microsite_target_city_state?: string;
  microsite_target_service?: string;
  microsite_target_category?: string;
  microsite_brand_mode?: 'all_major' | 'single_brand';
  microsite_selected_brand?: string;
}

export interface ServiceAreaDB {
  id: string;
  site_id: string;
  name: string;
  slug: string;
  state: string | null;
  place_id: string | null;
  latitude: number | null;
  longitude: number | null;
  distance_miles: number | null;
  is_custom: boolean;
  sort_order: number;
  // SEO fields (added for Phase 2)
  meta_title: string | null;
  meta_description: string | null;
  h1: string | null;
  body_copy: string | null;
  created_at: string;
  updated_at: string;
}

export interface Location {
  id: string;
  site_id: string;
  name: string;
  slug: string;
  address_line1: string;
  address_line2: string | null;
  city: string;
  state: string;
  zip_code: string;
  country: string;
  latitude: number | null;
  longitude: number | null;
  phone: string | null;
  is_primary: boolean;
  gbp_place_id: string | null;
  gbp_account_id: string | null;
  gbp_location_id: string | null;
  representative_city: string | null;
  representative_state: string | null;
  created_at: string;
  updated_at: string;
}

export interface GBPCategory {
  id: string;
  gcid: string; // Google Category ID
  name: string;
  display_name: string;
  parent_gcid: string | null;
  service_types: string[];
  created_at: string;
}

export interface SiteCategory {
  id: string;
  site_id: string;
  gbp_category_id: string;
  is_primary: boolean;
  sort_order: number;
  created_at: string;
}

export interface NeighborhoodLocalFeatures {
  landmarks: { name: string; description: string }[];
  schools: { name: string; description: string }[];
  housing: string;
  community: string;
  why_choose_us: string[];
}

export interface Neighborhood {
  id: string;
  site_id: string;
  location_id: string;
  name: string;
  slug: string;
  place_id: string | null;
  latitude: number | null;
  longitude: number | null;
  population: number | null;
  description: string | null;
  meta_title: string | null;
  meta_description: string | null;
  h1: string | null;
  body_copy: string | null;
  local_features: NeighborhoodLocalFeatures | null;
  faqs: { question: string; answer: string }[] | null;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ServiceProblem {
  heading: string;
  description: string;
}

export interface ServiceDetailedSection {
  h2: string;
  body: string;
  bullets: string[];
}

export interface Service {
  id: string;
  site_id: string;
  site_category_id: string;
  name: string;
  slug: string;
  description: string | null;
  // SEO fields
  meta_title: string | null;
  meta_description: string | null;
  h1: string | null;
  body_copy: string | null;
  faqs: ServiceFAQ[] | null;
  // Structured content fields
  intro_copy: string | null;
  problems: ServiceProblem[] | null;
  detailed_sections: ServiceDetailedSection[] | null;
  image_prompts: ImagePrompt[] | null;
  generated_images: GeneratedImage[] | null;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface GeneratedImage {
  url: string;
  storage_path: string;
  prompt_index: number;
  engine: 'openai' | 'nano_banana';
  width: number;
  height: number;
  created_at: string;
}

export interface ImagePrompt {
  image_type: 'hero' | 'category_support' | 'service' | 'environment';
  engine: 'openai' | 'nano_banana';
  page_type: 'home' | 'category' | 'service' | 'about' | 'contact' | 'location';
  section_type: 'hero' | 'grid' | 'background' | 'supporting';
  prompt: string;
  style: string;
  negative_prompt: string;
  reuse_strategy: 'new' | 'reuse_category';
  reuse_source_category_id?: string;
}

export interface ServiceFAQ {
  question: string;
  answer: string;
}

export type SitePageType = 'home' | 'about' | 'contact' | 'category' | 'service_area' | 'faq';

export interface AboutPageSections {
  founder_story?: { heading: string; paragraphs: string[] };
  mission_values?: { heading: string; paragraphs: string[] };
  experience_credentials?: { heading: string; paragraphs: string[]; highlights?: string[] };
  local_connection?: { heading: string; paragraphs: string[] };
  trust_points?: { heading: string; points: { title: string; description: string }[] };
  cta?: { heading: string; description: string };
}

export interface SitePage {
  id: string;
  site_id: string;
  location_id: string | null;
  category_id: string | null;
  page_type: SitePageType;
  slug: string;
  // SEO Content
  meta_title: string | null;
  meta_description: string | null;
  h1: string | null;
  h2: string | null;
  body_copy: string | null;
  hero_description: string | null;
  body_copy_2: string | null;
  faqs: ServiceFAQ[] | null;
  sections: AboutPageSections | null;
  image_prompts: ImagePrompt[] | null;
  generated_images: GeneratedImage[] | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export type LeadStatus = 'new' | 'contacted' | 'converted' | 'archived';

export interface Lead {
  id: string;
  site_id: string;
  name: string;
  email: string | null;
  phone: string | null;
  service_type: string | null;
  message: string | null;
  address: string | null;
  source_page: string | null;
  status: LeadStatus;
  created_at: string;
  updated_at: string;
}

export interface GoogleReview {
  id: string;
  site_id: string;
  location_id: string | null;
  google_review_id: string;
  author_name: string | null;
  author_photo_url: string | null;
  rating: number;
  comment: string | null;
  review_date: string | null;
  review_reply: string | null;
  reply_date: string | null;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export type WorkItemStatus = 'draft' | 'published';

export interface WorkItemImage {
  url: string;
  alt: string;
  width?: number;
  height?: number;
  role?: 'primary' | 'before' | 'after' | 'process' | 'detail';
  pairGroup?: number;
}

export interface WorkItem {
  id: string;
  site_id: string;
  status: WorkItemStatus;
  slug: string;
  performed_at: string | null;
  title: string;
  h1: string | null;
  meta_title: string | null;
  meta_description: string | null;
  summary: string | null;
  description: string | null;
  service_id: string | null;
  location_id: string | null;
  brand_name: string | null;
  brand_slug: string | null;
  images: WorkItemImage[];
  address_street_name: string | null;
  address_city: string | null;
  address_state: string | null;
  address_zip: string | null;
  created_at: string;
  updated_at: string;
}

export interface WorkItemWithRelations extends WorkItem {
  service?: { id: string; name: string; slug: string } | null;
  location?: { id: string; city: string; state: string; slug: string } | null;
}

export interface BrandValueProp {
  title: string;
  description: string;
}

export interface SiteBrand {
  id: string;
  site_id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  sort_order: number;
  is_active: boolean;
  // AI-generated content fields (populated by generate-content pipeline)
  meta_title: string | null;
  meta_description: string | null;
  h1: string | null;
  hero_description: string | null;
  body_copy: string | null;
  value_props: BrandValueProp[] | null;
  faqs: ServiceFAQ[] | null;
  cta_heading: string | null;
  cta_description: string | null;
  created_at: string;
  updated_at: string;
}

export interface JobSnap {
  id: string;
  site_id: string;
  service_id: string | null;
  created_by: string | null;
  title: string | null;
  description: string | null;
  ai_generated_title: string | null;
  ai_generated_description: string | null;
  service_type: string | null;
  brand: string | null;
  status: JobStatus;
  location_source: 'exif' | 'device' | 'manual' | null;
  address_full: string | null;
  address_public: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  latitude: number | null;
  longitude: number | null;
  is_published_to_website: boolean;
  is_published_to_gbp: boolean;
  approved_by: string | null;
  approved_at: string | null;
  deployed_at: string | null;
  work_item_id: string | null;
  is_before_after: boolean;
  created_at: string;
  updated_at: string;
}

export interface JobSnapMedia {
  id: string;
  job_snap_id: string;
  storage_path: string;
  file_name: string;
  ai_generated_name: string | null;
  alt_text: string | null;
  mime_type: string;
  file_size: number;
  width: number | null;
  height: number | null;
  exif_data: Record<string, unknown> | null;
  role: 'primary' | 'before' | 'after' | 'process' | 'detail' | null;
  pair_group: number | null;
  sort_order: number;
  created_at: string;
}

export interface SocialConnection {
  id: string;
  site_id: string;
  platform: 'google_business' | 'facebook' | 'instagram' | 'youtube';
  account_id: string;
  account_name: string;
  access_token: string;
  refresh_token: string | null;
  token_expires_at: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// Extended types with relations
export interface SiteWithRelations extends Site {
  locations?: Location[];
  categories?: (SiteCategory & { gbp_category: GBPCategory })[];
  services?: Service[];
  service_areas?: ServiceAreaDB[];
  site_pages?: SitePage[];
}

export interface LocationWithRelations extends Location {
  site?: Site;
  neighborhoods?: Neighborhood[];
}

export interface JobSnapWithRelations extends JobSnap {
  media?: JobSnapMedia[];
  service?: Service;
  created_by_profile?: Profile;
}

// Subscription types for Stripe integration
export type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'trialing' | 'incomplete';
export type PaymentStatus = 'succeeded' | 'failed' | 'pending' | 'refunded';

export interface SubscriptionPlan {
  id: string;
  name: string;
  display_name: string;
  price_cents: number;
  stripe_price_id: string;
  features: string[];
  is_active: boolean;
  created_at: string;
}

export interface Subscription {
  id: string;
  user_id: string;
  site_id: string | null;
  plan_id: string;
  stripe_subscription_id: string;
  stripe_customer_id: string;
  status: SubscriptionStatus;
  current_period_start: string | null;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  canceled_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface Payment {
  id: string;
  subscription_id: string;
  stripe_payment_intent_id: string | null;
  stripe_invoice_id: string | null;
  amount_cents: number;
  currency: string;
  status: PaymentStatus;
  created_at: string;
}

export interface SubscriptionWithPlan extends Subscription {
  plan?: SubscriptionPlan;
}

// ============================================================
// Scheduling System Types
// ============================================================

export type SchedulingMode = 'time_windows' | 'time_slots';
export type BookingMode = 'instant' | 'approval';
export type CTAStyle = 'booking' | 'estimate';
export type AppointmentSource = 'online_booking' | 'manual' | 'phone';
export type AppointmentStatus = 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
export type AvailabilityPostPlatform = 'google_business' | 'facebook';
export type AvailabilityPostStatus = 'pending' | 'published' | 'failed';

export interface SchedulingConfig {
  id: string;
  site_id: string;
  scheduling_mode: SchedulingMode;
  booking_mode: BookingMode;
  cta_style: CTAStyle;
  timezone: string;
  advance_booking_days: number;
  booking_buffer_minutes: number;
  show_availability_badge: boolean;
  auto_publish_availability: boolean;
  publish_times: string[];       // e.g. ["07:30","11:00","14:00"]
  publish_days: string[];        // e.g. ["mon","tue","wed","thu","fri"]
  notification_phone: string | null;
  notification_email: string | null;
  confirmation_message: string | null;
  twilio_phone_number: string | null;
  twilio_phone_sid: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface StaffSchedule {
  id: string;
  staff_member_id: string;
  scheduling_config_id: string;
  day_of_week: number;           // 0=Sun, 6=Sat
  start_time: string;            // TIME as string "HH:MM:SS"
  end_time: string;
  capacity: number;
  slot_times: string[] | null;   // for time_slots mode: ["08:00","09:00"]
  is_active: boolean;
  created_at: string;
}

export interface StaffTimeBlock {
  id: string;
  staff_member_id: string;
  block_date: string;            // DATE as string "YYYY-MM-DD"
  start_time: string | null;     // null = all day block
  end_time: string | null;
  reason: string | null;
  created_at: string;
}

export interface StaffServiceArea {
  id: string;
  staff_member_id: string;
  site_id: string;
  city: string | null;
  zip_code: string | null;
  service_area_id: string | null;
  created_at: string;
}

export interface Appointment {
  id: string;
  site_id: string;
  staff_member_id: string | null;
  lead_id: string | null;
  customer_name: string;
  customer_email: string | null;
  customer_phone: string | null;
  customer_city: string | null;
  customer_zip: string | null;
  service_type: string | null;
  notes: string | null;
  scheduled_date: string;        // DATE as "YYYY-MM-DD"
  scheduled_time: string | null; // TIME as "HH:MM:SS"
  time_window_start: string | null;
  time_window_end: string | null;
  source: AppointmentSource;
  status: AppointmentStatus;
  reminder_24h_sent: boolean;
  reminder_dayof_sent: boolean;
  confirmation_sent: boolean;
  created_at: string;
  updated_at: string;
}

export interface DateOverride {
  id: string;
  scheduling_config_id: string;
  override_date: string;         // DATE as "YYYY-MM-DD"
  is_blocked: boolean;
  reason: string | null;
  created_at: string;
}

export interface AvailabilityPost {
  id: string;
  site_id: string;
  platform: AvailabilityPostPlatform;
  post_content: string;
  spots_available: number;
  posted_date: string;           // DATE as "YYYY-MM-DD"
  external_post_id: string | null;
  status: AvailabilityPostStatus;
  error_message: string | null;
  created_at: string;
}

// Extended scheduling types
export interface AppointmentWithStaff extends Appointment {
  staff_member?: StaffMember;
}

export interface AppointmentWithLead extends Appointment {
  lead?: Lead;
  staff_member?: StaffMember;
}

export interface StaffMemberWithSchedule extends StaffMember {
  schedules?: StaffSchedule[];
  time_blocks?: StaffTimeBlock[];
  service_areas?: StaffServiceArea[];
}

export interface GSCQuery {
  id: string;
  site_id: string;
  query: string;
  page_url: string | null;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
  date_range_start: string;
  date_range_end: string;
  fetched_at: string;
  created_at: string;
}
